baseURL = 'https://pixelpromenade.eu/'
languageCode = 'fr'
title = 'Pixel Promenade'
theme = 'dream'

[params]
  lightTheme = "emerald"
  darkTheme = "forest"

  author = "Kaz"
  description = "Un blog expérimental."
  avatar = "img/personal/avatar.jpg"
  

  defaultTheme = "light"

  headerTitle = "Pixel Promenade"
  motto = "Un article par semaine - du café et des livres"


  footerBottomText = "Blog expérimental - Un article par semaine"

  zenMode = true

  siteStartYear = 2025

  ShowShareButtons = false
  reorderShares = [""]



[[menu.main]]
  identifier = "about"
  name = "À Propos"
  url = "/about/"

[[menu.main]]
  identifier = "posts"
  name = "Articles"
  url = "/posts/"

[markup]
  [markup.goldmark.parser.attribute]
  block = true